// Parser Result Errors indicate a problem with the expected result generated by the parser.
// They are internal errors and not the fault of the user.

class ParserResultError extends Error {
	constructor(message) {
		super(message)
		console.log("Parser Result Error: This is an internal error and not your fault.")
	}
}

module.exports = ParserResultError